import Head from 'next/head';
import   { ReactNode } from "react";

import Footer from'./footer'

interface Props {
  children?: ReactNode
  // any props that come into the component
}

const Layout = ({ children }:Props) => {
  return (
    <>
      <Head>
        <title>Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}

      <Footer />
    </>
  );
};
export default Layout;