import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import dynamic from 'next/dynamic';

const Footer = dynamic(() => import('hub/components/footer'));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className='text-red-500'>this is news001 project</h1>
      </main>
      <Footer />
    </>
  );
}
